# Generated by Django 6.0.5 on 2026-05-29 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='allowed_faculty',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty',
        ),
    ]
