# Generated by Django 6.0.5 on 2026-05-29 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0002_remove_election_allowed_faculty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='allowed_faculty',
            field=models.CharField(blank=True, help_text='Leave blank for university-wide elections', max_length=100, null=True),
        ),
    ]
